[package]
name = "use-pip"
description = "pip command and requirement metadata primitives for RustUse"
publish = true
autoexamples = false
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-pip"
keywords = ["python", "pip", "metadata"]
categories = ["development-tools"]

[[example]]
name = "pip_basic_usage"
path = "examples/basic_usage.rs"

[lints]
workspace = true
