[workspace]
members = [
    "crates/use-python",
    "crates/use-python-version",
    "crates/use-python-identifier",
    "crates/use-python-keyword",
    "crates/use-python-value",
    "crates/use-python-module",
    "crates/use-pyproject",
    "crates/use-pip",
    "crates/use-uv",
    "crates/use-venv",
    "crates/use-pytest",
]
resolver = "2"

[workspace.package]
authors = ["RustUse Contributors"]
edition = "2024"
homepage = "https://rustuse.org"
license = "MIT OR Apache-2.0"
publish = false
readme = "README.md"
repository = "https://github.com/RustUse/use-python"
rust-version = "1.95.0"
version = "0.0.1"

[workspace.dependencies]
use-pip = { version = "0.0.1", path = "crates/use-pip" }
use-pyproject = { version = "0.0.1", path = "crates/use-pyproject" }
use-pytest = { version = "0.0.1", path = "crates/use-pytest" }
use-python-identifier = { version = "0.0.1", path = "crates/use-python-identifier" }
use-python-keyword = { version = "0.0.1", path = "crates/use-python-keyword" }
use-python-module = { version = "0.0.1", path = "crates/use-python-module" }
use-python-value = { version = "0.0.1", path = "crates/use-python-value" }
use-python-version = { version = "0.0.1", path = "crates/use-python-version" }
use-uv = { version = "0.0.1", path = "crates/use-uv" }
use-venv = { version = "0.0.1", path = "crates/use-venv" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.metadata.rustuse.release]
publish = false
versioning = "lockstep-0.x"
first-publish-candidates = [
    "use-python-keyword",
    "use-python-version",
    "use-python-value",
    "use-pyproject",
    "use-pip",
    "use-uv",
    "use-venv",
    "use-python-identifier",
    "use-python-module",
    "use-pytest",
    "use-python",
]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
expect_used = "warn"
multiple_crate_versions = "allow"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
todo = "deny"
unimplemented = "deny"
unwrap_used = "warn"
